In [1]:
import numpy as np
mnist_filename = 'mnist_kaggle_some_rows.csv'
data = np.loadtxt(mnist_filename, delimiter=',')
print(data)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]]
